require("lib")

_G.c = require("common.util")
_G.c.report = require("common.report")
_G.c.state = require("common.state")
_G.c.item = require("common.item")
_G.c.chest = require("common.chest")
_G.c.craft = require("common.craft")
_G.c.dig = require("common.dig")
_G.c.fuel = require("common.fuel")
_G.c.goal = require("common.goal")
_G.c.inspect = require("common.inspect")
_G.c.inventory = require("common.inventory")
_G.c.leaf = require("common.leaf")
_G.c.move = require("common.move")
_G.c.task = require("common.task")
_G.c.scan = require("common.scan")
_G.c.tree = require("common.tree")
_G.c.turn = require("common.turn")
_G.c.mine = require("common.mine")
_G.c.relativeGps = require("common.relativeGps")
_G.c.gps = require("common.gps")
_G.c.vector = require("common.vector")
_G.c.location = require("common.location")
