require("lib")

_G.c = require("src.common.util")
_G.c.report = require("src.common.report")
_G.c.task = require("src.common.task")
_G.c.state = require("src.common.state")
_G.c.item = require("src.common.item")
_G.c.recipe = require("src.common.recipe")
_G.c.turn = require("src.common.turn")
_G.c.stash = require("src.common.stash")
_G.c.craft = require("src.common.craft")
_G.c.dig = require("src.common.dig")
_G.c.fuel = require("src.common.fuel")
_G.c.smelt = require("src.common.smelt")
_G.c.goal = require("src.common.goal")
_G.c.inspect = require("src.common.inspect")
_G.c.inventory = require("src.common.inventory")
_G.c.leaf = require("src.common.leaf")
_G.c.move = require("src.common.move")
_G.c.scan = require("src.common.scan")
_G.c.tree = require("src.common.tree")
_G.c.mine = require("src.common.mine")
_G.c.gpsNext = require("src.common.gpsNext")
_G.c.gpsRelative = require("src.common.gpsRelative")
_G.c.gps = require("src.common.gps")
_G.c.vector = require("src.common.vector")
_G.c.location = require("src.common.location")
